/* ============================================================
   IMÁGENES DE PRODUCTOS — Mayorista a tu Casa
   Son ilustraciones genéricas por tipo de producto (no muestran la marca).
   Origen: Fluent Emoji 3D de Microsoft (licencia MIT, ver img/productos/LICENCIA.txt).

   Para usar una FOTO propia de un producto:
   1) Guardá la foto en img/fotos/ (cuadrada, JPG o WEBP, de unos 300 x 300 px).
   2) Agregala en "fotos" con el código del producto. Ejemplo:
        fotos: { "M72": "img/fotos/playadito-500.jpg" }
   La foto reemplaza a la ilustración solo en ese producto.
   Si un producto nuevo no figura en "tipoPorProducto", se muestra el ícono del rubro.
   ============================================================ */
window.IMAGENES_TIENDA = {
  carpeta: "img/productos/",
  fotos: {},
  tipos: {
    "aceite": "aceite de girasol",
    "aceitunas": "aceitunas",
    "aceitunas-negras": "aceitunas negras",
    "afeitar": "máquina de afeitar",
    "agua": "agua",
    "ajies": "ajíes",
    "alcohol": "alcohol",
    "alfajor": "alfajor",
    "anchoas": "anchoas",
    "aperitivo": "aperitivo",
    "arroz": "arroz",
    "arvejas": "arvejas",
    "atun": "atún",
    "azucar": "azúcar",
    "batata": "dulce de batata",
    "bizcochos": "bizcochos",
    "bizcochuelo": "bizcochuelo",
    "brownie": "brownie",
    "cacao": "cacao en polvo",
    "cafe": "café",
    "caldo": "caldo",
    "chizitos": "chizitos",
    "choclo": "choclo",
    "conserva": "conserva",
    "crema": "crema",
    "crema-limpiadora": "limpiador en crema",
    "desinfectante": "desinfectante",
    "desodorante": "desodorante",
    "detergente": "detergente",
    "dulce-de-leche": "dulce de leche",
    "durazno": "duraznos",
    "encendedor": "encendedor",
    "endulzante": "endulzante",
    "endulzante-liquido": "endulzante líquido",
    "energizante": "bebida energizante",
    "fernet": "aperitivo",
    "fiambre": "fiambre",
    "fideos": "fideos",
    "galletitas-dulces": "galletitas dulces",
    "galletitas-saladas": "galletitas",
    "grasa-cerdo": "grasa de cerdo",
    "grasa-vaca": "grasa vacuna",
    "guantes": "guantes",
    "harina": "harina",
    "insecticida": "insecticida",
    "jabon-pan": "jabón en pan",
    "jabon-ropa": "jabón para ropa",
    "jabon-tocador": "jabón de tocador",
    "jamon": "jamón",
    "jugo": "jugo",
    "jugo-polvo": "jugo en polvo",
    "lavandina": "lavandina",
    "mani": "maní",
    "manteca": "manteca",
    "mate-cocido": "mate cocido",
    "mayonesa": "mayonesa",
    "membrillo": "dulce de membrillo",
    "mermelada-durazno": "mermelada",
    "mermelada-frutilla": "mermelada",
    "mostaza": "mostaza",
    "obleas": "obleas",
    "palitos": "palitos salados",
    "pan-rallado": "pan rallado",
    "panceta": "panceta",
    "papas": "papas fritas",
    "papel-higienico": "papel higiénico",
    "pasta-dental": "pasta dental",
    "pickles": "pickles",
    "pilas": "pilas",
    "pisos": "limpiador de pisos",
    "pizza": "salsa para pizza",
    "pochoclo": "pochoclo",
    "pollo": "pollo",
    "queso": "queso",
    "rollo-cocina": "rollo de cocina",
    "sal": "sal",
    "salchichas": "salchichas",
    "shampoo": "shampoo",
    "suavizante": "suavizante",
    "te": "té",
    "tomate": "tomate",
    "turron": "turrón de maní",
    "vinagre": "vinagre",
    "vino": "vino",
    "yerba": "yerba mate",
    "yogur": "yogur"
  },
  tipoPorProducto: {"M2": "manteca", "M3": "manteca", "M4": "grasa-vaca", "M5": "grasa-cerdo", "M6": "aceitunas", "M7": "aceitunas", "M8": "aceitunas", "M14": "aceitunas", "M15": "aceitunas", "M16": "aceitunas", "M17": "aceitunas", "M9": "aceitunas-negras", "M10": "ajies", "M11": "pickles", "M13": "pickles", "M12": "anchoas", "M18": "conserva", "M19": "azucar", "M114": "azucar", "M28": "pochoclo", "M219": "pochoclo", "M29": "cacao", "M30": "cacao", "M53": "agua", "M54": "agua", "M20": "fideos", "M21": "fideos", "M22": "fideos", "M23": "fideos", "M24": "arroz", "M25": "arroz", "M26": "arroz", "M27": "arroz", "M31": "tomate", "M32": "tomate", "M33": "tomate", "M34": "tomate", "M35": "tomate", "M36": "choclo", "M37": "arvejas", "M38": "pizza", "M39": "durazno", "M40": "atun", "M41": "atun", "M42": "atun", "M43": "aceite", "M44": "aceite", "M45": "aceite", "M46": "aceite", "M47": "aceite", "M48": "vinagre", "M49": "caldo", "M50": "caldo", "M51": "harina", "M52": "harina", "M55": "sal", "M56": "sal", "M57": "sal", "M58": "pan-rallado", "M59": "pan-rallado", "M60": "pan-rallado", "M61": "mayonesa", "M62": "mayonesa", "M63": "mayonesa", "M64": "mayonesa", "M65": "mayonesa", "M67": "mayonesa", "M66": "mostaza", "M68": "pilas", "M69": "pilas", "M70": "yerba", "M71": "yerba", "M72": "yerba", "M73": "yerba", "M74": "yerba", "M75": "yerba", "M76": "yerba", "M77": "yerba", "M78": "yerba", "M79": "yerba", "M80": "yerba", "M81": "yerba", "M82": "yerba", "M83": "yerba", "M84": "yerba", "M85": "yerba", "M86": "yerba", "M87": "cafe", "M88": "cafe", "M89": "cafe", "M90": "cafe", "M91": "cafe", "M92": "te", "M93": "te", "M94": "te", "M95": "te", "M96": "te", "M97": "mate-cocido", "M98": "mate-cocido", "M99": "mate-cocido", "M100": "mate-cocido", "M101": "mermelada-durazno", "M137": "mermelada-durazno", "M140": "mermelada-durazno", "M102": "mermelada-frutilla", "M138": "mermelada-frutilla", "M139": "mermelada-frutilla", "M141": "mermelada-frutilla", "M142": "mermelada-frutilla", "M143": "mermelada-frutilla", "M144": "mermelada-frutilla", "M103": "bizcochuelo", "M104": "bizcochuelo", "M106": "bizcochuelo", "M105": "brownie", "M107": "dulce-de-leche", "M108": "dulce-de-leche", "M109": "dulce-de-leche", "M110": "alfajor", "M111": "alfajor", "M112": "alfajor", "M113": "turron", "M115": "endulzante", "M116": "endulzante", "M117": "endulzante-liquido", "M118": "endulzante-liquido", "M119": "galletitas-saladas", "M120": "galletitas-saladas", "M122": "galletitas-saladas", "M126": "galletitas-saladas", "M130": "galletitas-saladas", "M131": "galletitas-saladas", "M132": "galletitas-saladas", "M135": "galletitas-saladas", "M136": "galletitas-saladas", "M121": "galletitas-dulces", "M123": "galletitas-dulces", "M124": "galletitas-dulces", "M128": "galletitas-dulces", "M129": "galletitas-dulces", "M133": "galletitas-dulces", "M125": "obleas", "M134": "obleas", "M127": "bizcochos", "M145": "yogur", "M146": "queso", "M147": "queso", "M148": "queso", "M149": "queso", "M150": "queso", "M151": "queso", "M152": "queso", "M153": "queso", "M154": "queso", "M155": "queso", "M156": "queso", "M157": "queso", "M158": "queso", "M159": "queso", "M160": "queso", "M161": "queso", "M162": "queso", "M163": "queso", "M164": "queso", "M165": "queso", "M166": "queso", "M167": "jamon", "M168": "jamon", "M169": "jamon", "M170": "jamon", "M171": "jamon", "M172": "jamon", "M173": "jamon", "M174": "jamon", "M175": "jamon", "M176": "jamon", "M177": "jamon", "M178": "fiambre", "M179": "fiambre", "M181": "fiambre", "M182": "fiambre", "M183": "fiambre", "M184": "fiambre", "M185": "fiambre", "M186": "fiambre", "M187": "fiambre", "M188": "fiambre", "M189": "fiambre", "M190": "fiambre", "M191": "fiambre", "M192": "fiambre", "M193": "fiambre", "M194": "fiambre", "M195": "fiambre", "M196": "fiambre", "M197": "fiambre", "M180": "panceta", "M198": "pollo", "M199": "salchichas", "M200": "batata", "M202": "batata", "M204": "batata", "M201": "membrillo", "M203": "membrillo", "M205": "membrillo", "M206": "papas", "M207": "papas", "M213": "papas", "M214": "papas", "M218": "papas", "M208": "chizitos", "M209": "chizitos", "M215": "chizitos", "M210": "palitos", "M216": "palitos", "M211": "mani", "M212": "mani", "M217": "mani", "M220": "mani", "M221": "mani", "M222": "vino", "M223": "vino", "M224": "vino", "M225": "vino", "M226": "vino", "M227": "jugo-polvo", "M228": "jugo-polvo", "M229": "jugo", "M230": "fernet", "M231": "fernet", "M232": "aperitivo", "M233": "aperitivo", "M234": "energizante", "M235": "energizante", "M236": "energizante", "M237": "detergente", "M238": "detergente", "M239": "detergente", "M240": "detergente", "M241": "detergente", "M242": "crema-limpiadora", "M243": "rollo-cocina", "M244": "rollo-cocina", "M245": "rollo-cocina", "M246": "jabon-pan", "M247": "jabon-pan", "M248": "insecticida", "M249": "insecticida", "M250": "alcohol", "M251": "desinfectante", "M252": "desinfectante", "M273": "encendedor", "M274": "guantes", "M253": "jabon-ropa", "M254": "jabon-ropa", "M255": "jabon-ropa", "M256": "jabon-ropa", "M257": "jabon-ropa", "M258": "jabon-ropa", "M259": "jabon-ropa", "M260": "jabon-ropa", "M261": "jabon-ropa", "M262": "lavandina", "M263": "lavandina", "M264": "lavandina", "M265": "lavandina", "M266": "lavandina", "M267": "lavandina", "M268": "lavandina", "M269": "lavandina", "M270": "pisos", "M271": "pisos", "M272": "suavizante", "M275": "shampoo", "M276": "shampoo", "M277": "shampoo", "M278": "shampoo", "M279": "papel-higienico", "M280": "papel-higienico", "M281": "papel-higienico", "M282": "papel-higienico", "M283": "papel-higienico", "M284": "papel-higienico", "M285": "papel-higienico", "M286": "papel-higienico", "M287": "jabon-tocador", "M288": "jabon-tocador", "M289": "jabon-tocador", "M290": "jabon-tocador", "M291": "desodorante", "M292": "desodorante", "M293": "desodorante", "M294": "desodorante", "M295": "afeitar", "M296": "afeitar", "M297": "afeitar", "M298": "afeitar", "M299": "pasta-dental", "M300": "pasta-dental", "M301": "pasta-dental", "M302": "pasta-dental", "M303": "pasta-dental", "M304": "crema"}
};
